apiVersion: v2
name: circleci-server-monitoring-stack
description: A reference Helm chart for setting up a monitoring stack for CircleCI server
version: 0.1.0
dependencies:
  - name: prometheus-operator-crds
    version: 18.0.1
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheusOperatorCRDs.install
  - name: grafana-operator
    version: 5.16.0
    repository: "https://grafana.github.io/helm-charts"
    alias: grafanaoperator
