apiVersion: v2
name: server-monitoring-stack
description: A reference Helm chart for setting up a monitoring stack for CircleCI server
version: 0.1.0-alpha.6
dependencies:
  - name: prometheus-operator-crds
    version: 19.0.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheusOperator.installCRDs
    alias: prometheusOperator
  - name: grafana-operator
    version: v5.18.0
    repository: "https://grafana.github.io/helm-charts"
    alias: grafanaoperator
    condition: grafanaoperator.enabled
