{{- include "grafana.enabled" . -}}
{{- if .grafanaEnabled }}
{{- $name := include "server-monitoring.fullname" . -}}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ $name }}-prometheus-datasource
spec:
  datasource:
    access: proxy
    type: prometheus
    jsonData:
      timeInterval: {{ .Values.grafana.datasource.jsonData.timeInterval }}
      tlsSkipVerify: true
    name: Prometheus
    url: http://{{ $name }}-prometheus:9090
  instanceSelector:
    matchLabels:
      dashboards: grafana
{{- end }}
