{{- with .Values.grafana.persistence }}
{{- if .enabled }}
{{- $name := include "server-monitoring.fullname" $ -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-grafana-pvc
  labels:
    app: {{ $name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .size }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
