{{- include "grafana.enabled" . -}}
{{- if .grafanaEnabled }}
{{- $name := include "server-monitoring.fullname" $ -}}
{{- with .Values.grafana.credentials }}
{{- if not .existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-grafana-credentials
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .adminUser }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .adminPassword }}
{{- end }}
{{- end }}
{{- end }}
