{{- include "prometheusOperator.enabled" . -}}
{{- if .prometheusOperatorEnabled }}
{{- $name := include "server-monitoring.fullname" . -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: {{ .Values.prometheusOperator.image.tag }}
  name: {{ $name }}-prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}-prometheus-operator
subjects:
  - kind: ServiceAccount
    name: {{ $name }}-prometheus-operator
    namespace:  {{ .Release.Namespace }}
{{- end }}
