{{- include "prometheusOperator.enabled" . -}}
{{- if .prometheusOperatorEnabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: {{ .Values.prometheusOperator.image.tag }}
  name: {{ include "server-monitoring.fullname" . }}-prometheus-operator
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
{{- end }}
