{{- $name := include "server-monitoring.fullname" . -}}

{{- with .Values.prometheus.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}-prometheus
  labels:
    app: {{ $name }}-prometheus
spec:
  selector:
    matchLabels:
{{ toYaml .selectorLabels | indent 6 }}
{{- if .selectorNamespaces }}
  namespaceSelector:
    matchNames:
{{ toYaml .selectorNamespaces | indent 6 }}
{{- end }}
  endpoints:
{{ toYaml .endpoints | indent 4 }}
{{- end }}
